python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 0 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 0 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 0 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 0 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 1 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 1 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 1 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 1 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 2 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 2 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 2 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 2 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 3 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 3 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 3 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 3 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 0 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 0 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 0 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 0 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 0 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 0 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 0 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 0 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 1 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 1 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 1 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 1 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 2 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 2 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 2 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 2 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 3 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 3 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 3 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 3 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 1 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 1 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 1 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 1 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 0 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 0 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 0 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 0 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 1 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 1 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 1 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 1 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 2 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 2 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 2 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 2 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 3 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 3 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 3 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 3 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 30 --seed 2 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 45 --seed 2 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 60 --seed 2 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
python experiment_refrac.py --rotation-angle 90 --seed 2 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048
