python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen1_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen1_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen2_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen2_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen3_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen3_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen1_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen1_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen2_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen2_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen3_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen3_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen1_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen1_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen2_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen2_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen3_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen3_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen1_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen1_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen2_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen2_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen3_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 0 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen3_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen1_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen1_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen2_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen2_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen3_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen3_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen1_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen1_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen2_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen2_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen3_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen3_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen1_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen1_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen2_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen2_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen3_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int2_gen3_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen3_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen1_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int3_gen1_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen1_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen2_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int3_gen2_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen2_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen3_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int3_gen3_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 1 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen3_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen1_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int0_gen1_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen1_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen2_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int0_gen2_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen2_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen3_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int0_gen3_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int0_gen3_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen1_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int1_gen1_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen1_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen2_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int1_gen2_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen2_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen3_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int1_gen3_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int1_gen3_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen1_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int2_gen1_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen1_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen2_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int2_gen2_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen2_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen3_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int2_gen3_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int2_gen3_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen1_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int3_gen1_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen1_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen2_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int3_gen2_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen2_pseudo_pseudo_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen3_pseudo_prototypes_bic_em-ensemble
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --log-file test_acc_dim2048_int3_gen3_pseudo_pseudo_bic
python experiment_refrac.py --dataset color_mnist --seed 2 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 2048 --em-ensemble --log-file test_acc_dim2048_int3_gen3_pseudo_pseudo_bic_em-ensemble
