python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 0 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 1 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 2 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 3 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 0 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 0 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 1 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 2 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 3 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 1 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 0 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 0 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 0 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 0 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 1 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 1 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 1 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 1 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 2 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 2 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 2 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 2 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 3 --generated-domains 0 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 3 --generated-domains 1 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 3 --generated-domains 2 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match prototypes --em-select bic --small-dim 54 --em-ensemble
python experiment_refrac.py --dataset covtype --seed 2 --gt-domains 3 --generated-domains 3 --label-source pseudo --em-match pseudo --em-select bic --small-dim 54 --em-ensemble
